# This is a basic workflow to help you get started with Actions

name: ci-build-windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    outputs:
      essential-binaries: ${{ steps.archive-essential-binaries.outputs.artifact-id }}
      all-binaries: ${{ steps.archive-all-binaries.outputs.artifact-id }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: recursive
      - name: couble-checking-submodules
        run: |-
          git submodule update --init --recursive
      - name: choco-install-ninja
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install ninja
      - name: Configure Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: run-windows-build
        shell: pwsh
        run: |-
          ./mips_only_build.ps1
      - name: preparing-essential-distribution
        shell: pwsh
        run: |-
          ./prepare_min_dist.ps1
      - name: archive-essential-binaries
        uses: actions/upload-artifact@v4
        with:
          name: n64recomp-clang-essentials-${{ runner.os }}
          path: |
            ./build/bin_essentials/*
      - name: archive-all-binaries
        uses: actions/upload-artifact@v4
        with:
          name: n64recomp-clang-${{ runner.os }}
          path: |
            ./build/bin/*
        
