name: build-dev-branch
on:
  push:
    branches: [ "dev" ]
    tags:        
      - 'dev-build/*'
jobs:
  build-windows: 
    uses: LT-Schmiddy/n64recomp-clang/.github/workflows/run-build-windows.yml@dev
    if: startsWith(github.ref, 'refs/tags/')


      
