name: publish-release
on:
  push:
    tags:        
      - 'release-*.*.*'
jobs:
  build-windows: 
    uses: LT-Schmiddy/n64recomp-clang/.github/workflows/run-build-windows.yml@master
  build-ubuntu:
    uses: LT-Schmiddy/n64recomp-clang/.github/workflows/run-build-ubuntu.yml@master
  publish-release:
    runs-on: windows-latest
    needs: build-windows build-ubuntu
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          # submodules: recursive
      - name: Get Artifacts
        uses: actions/download-artifact@v4
        with:
          path: $GITHUB_WORKSPACE/archives
      - name: choco-install-ninja-python
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install python
      - name: Configure Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: run-windows-build
        run: |-
          python ./generate_release_message.py
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/_release.md
          files: |
            $GITHUB_WORKSPACE/archives/*/*
          make_latest: true
      
