name: publish-release
on:
  push:
    tags:        
      - 'release-*.*.*'
jobs:
  build-windows: 
    uses: LT-Schmiddy/n64recomp-clang/.github/workflows/run-build-windows.yml@master
    with:
      script-args: dummy
  publish-release:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          submodules: recursive
      - name: Get Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./uploads
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: |
            ./uploads/*
          make_latest: true
      
