name: publish-release
on:
  push:
    tags:        
      - 'release-*.*.*'
jobs:
  build-windows: 
    uses: LT-Schmiddy/n64recomp-clang/.github/workflows/run-build-windows.yml@master
    with:
      script-args: dummy
  publish-release:
    runs-on: windows-latest
    needs: build-windows
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          # submodules: recursive
      - name: Get Artifacts
        uses: actions/download-artifact@v4
        with:
          path: $GITHUB_WORKSPACE/archives
      - name: choco-install-python
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install python
      - name: info-script
        shell: python
        run: |
          import os, shutil
          from pathlib import Path
          # Printing dir tree:
          print(f"{os.getcwd()=}")
          for root, dirs, files in os.walk(os.getcwd()):
            if ".git" in root:
              continue

            print("Directory:", root)
            print("Subdirectories:")
            for dir in dirs:
              print(f"\t{dir}")

            print("Files:")
            for file in files:
              print(f"\t{file}")
            
            print("-" * 20)

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          files: |
            $GITHUB_WORKSPACE/archives/essentials-Windows/*
            $GITHUB_WORKSPACE/archives/full-Windows/*
          make_latest: true
      
